#cloud-config
package_update: true

runcmd:
  # 1. Install necessary packages for QEMU and NFS server
  - apt install -y qemu-kvm nfs-kernel-server net-tools

  # 2. Create and prepare NFS shared directory
  - mkdir -p /mnt/nfs
  - chown nobody:nogroup /mnt/nfs
  - chmod 777 /mnt/nfs

  # 3. Create QEMU disk image (10G)
  - qemu-img create -f qcow2 /mnt/nfs/ubuntu.qcow2 10G

  # 4. Configure NFS exports (using echo append to file)
  - echo "/mnt/nfs *(rw,sync,no_subtree_check,no_root_squash)" >> /etc/exports

  # 5. Apply NFS export rules
  - exportfs -arv

final_message: "Start guest1"

# Steps to launch guest1:
## multipass launch -m 4G -d 20G -c 2 -n guest1 --cloud-init=guest1.yaml
## multipass shell guest1
## sudo su
## Launch QEMU Guest 1 ... (lin32)
## qemu-system-x86_64 -cpu host -enable-kvm -m 2G -smp 1 -drive if=virtio,format=qcow2,file=/mnt/nfs/ubuntu.qcow2 -monitor telnet:0:5500,server,nowait -display curses

# If need to relaunch new updated .yaml, need to delete and purge first:
## multipass delete guest1
## multipass purge
## Then relaunch with new .yaml file

# Check status:
## multipass list
