#cloud-config
package_update: true

runcmd:
  # 1. Install necessary packages for QEMU and NFS client
  - apt install -y qemu-kvm net-tools nfs-common

  # 2. Create NFS mount point
  - mkdir -p /mnt/nfs

  # 3. Mount NFS share from guest1 (Need guest1's IP address)
  # - mount -t nfs <guest1_ip>:/mnt/nfs /mnt/nfs
  # - mount -t nfs 10.221.208.111:/mnt/nfs /mnt/nfs；due to "10.221.208.111" is dynamic IP, so use below command to get it
  - mount -t nfs guest1:/mnt/nfs /mnt/nfs

final_message: "Start guest2"

# Steps to launch guest2:
## multipass launch -m 4G -d 20G -c 2 -n guest2 --cloud-init=guest2.yaml
## multipass shell guest2
## sudo su
## Launch QEMU Guest 2 ... (lin23)
## qemu-system-x86_64 -cpu host -enable-kvm -m 2G -smp 1 -drive if=virtio,format=qcow2,file=/mnt/nfs/ubuntu.qcow2 -incoming tcp:0:4400 -display curses

# If need to relaunch new updated .yaml, need to delete and purge first:
## If not able to delete, first do: multipass stop guest2 --force
## Then: multipass delete guest2
## multipass purge
## Then relaunch with new .yaml file

# Check status:
## multipass list
